#!/usr/bin/env python3
"""CLI routing and failure cleanup with fake tools; never connects to a real device."""
import contextlib
import io
import os
from pathlib import Path
import subprocess
import tempfile
from types import SimpleNamespace
import unittest
from unittest.mock import patch

import package_apk
import tv


def result(stdout="", stderr="", code=0):
    return subprocess.CompletedProcess([], code, stdout, stderr)


class ContextTestCase(unittest.TestCase):
    """Register context cleanup without Python 3.11's TestCase.enterContext."""

    def enter_context(self, manager):
        stack = contextlib.ExitStack()
        self.addCleanup(stack.close)
        return stack.enter_context(manager)


class EnvironmentTests(ContextTestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory(prefix="jzmedia-tv-cli-")
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name).resolve()
        self.project = self.root / "android-tv"
        self.project.mkdir()
        (self.project / "app").mkdir()
        (self.project / "app/build.gradle.kts").write_text('compileSdk = 36\nbuildToolsVersion = "36.0.0"\n', encoding="utf-8")
        self.enter_context(patch.object(tv, "PROJECT", self.project))
        self.enter_context(patch.dict(os.environ, {}, clear=True))
        self.enter_context(patch.object(tv.Path, "home", return_value=self.root / "home"))

    def binary(self, path):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("fake executable", encoding="utf-8")
        path.chmod(0o755)
        return path

    def test_local_sdk_properties_override_environment_and_unescape_spaces(self):
        sdk = self.root / "Android SDK"
        escaped = str(sdk).replace("\\", "\\\\").replace(" ", "\\ ")
        (self.project / "local.properties").write_text(f"# generated by Studio\nsdk.dir={escaped}\n", encoding="utf-8")
        with patch.dict(os.environ, {"ANDROID_HOME": "wrong", "ANDROID_SDK_ROOT": "also-wrong"}):
            self.assertEqual(tv.sdk_location(), sdk)

    def test_sdk_properties_unicode_escapes_resolve_to_the_real_chinese_directory(self):
        sdk = self.root / "周" / "Android SDK"
        self.binary(sdk / "platforms/android-36/android.jar")
        self.binary(sdk / "build-tools/36.0.0" / tv.executable_name("aapt2"))
        escaped = str(sdk).replace("\\", "\\\\").replace(" ", "\\ ").replace("周", r"\u5468")
        (self.project / "local.properties").write_text(f"sdk.dir={escaped}\n", encoding="utf-8")
        with patch.dict(os.environ, {"ANDROID_HOME": "wrong"}):
            self.assertEqual(tv.sdk_location(), sdk)
            self.assertEqual(tv.require_sdk(), sdk)

    def test_properties_decode_windows_paths_control_escapes_and_surrogate_pairs(self):
        self.assertEqual(tv.property_value(r"C\:\\Users\\\u5468\\Android\ SDK"), "C:\\Users\\周\\Android SDK")
        self.assertEqual(tv.property_value(r"literal-周\n\r\t\f\ \!"), "literal-周\n\r\t\f !")
        self.assertEqual(tv.property_value(r"\uD83D\uDE00"), "😀")
        self.assertEqual(tv.property_value(r"literal\\u5468"), r"literal\u5468")
        for invalid in (r"\u12", r"\uZZZZ", r"\uD83D"):
            with self.subTest(invalid=invalid), self.assertRaisesRegex(tv.ToolError, "Unicode"):
                tv.property_value(invalid)

    def test_sdk_environment_priority_and_no_silent_fallback_for_invalid_config(self):
        with patch.dict(os.environ, {"ANDROID_HOME": str(self.root / "missing"), "ANDROID_SDK_ROOT": str(self.root)}):
            self.assertEqual(tv.sdk_location(), self.root / "missing")
            with self.assertRaisesRegex(tv.ToolError, "未找到 Android SDK"):
                tv.require_sdk()

    def test_windows_and_macos_default_sdk_paths_and_windows_adb(self):
        for platform, sdk in (("win32", self.root / "Local/Android/Sdk"),
                              ("darwin", self.root / "home/Library/Android/sdk")):
            with self.subTest(platform=platform), patch.object(tv.sys, "platform", platform), \
                    patch.dict(os.environ, {"LOCALAPPDATA": str(self.root / "Local")}):
                sdk.mkdir(parents=True)
                self.assertEqual(tv.sdk_location(), sdk)
                binary = self.binary(sdk / "platform-tools" / tv.executable_name("adb"))
                self.assertEqual(tv.find_adb(), str(binary))

    def test_sdk_components_are_read_from_the_build_file(self):
        sdk = self.root / "sdk"
        sdk.mkdir()
        with patch.dict(os.environ, {"ANDROID_HOME": str(sdk)}):
            with self.assertRaisesRegex(tv.ToolError, "Platform 36.*Build-Tools 36.0.0"):
                tv.require_sdk()
            self.binary(sdk / "platforms/android-36/android.jar")
            self.binary(sdk / "build-tools/36.0.0" / tv.executable_name("aapt2"))
            self.assertEqual(tv.require_sdk(), sdk)

    def test_configured_java_requires_a_jdk_and_does_not_choose_another_installation(self):
        java_home = self.root / "jre"
        self.binary(java_home / "bin" / tv.executable_name("java"))
        with patch.dict(os.environ, {"JAVA_HOME": str(java_home)}), patch.object(tv.shutil, "which") as which:
            with self.assertRaisesRegex(tv.ToolError, "没有完整 JDK"):
                tv.require_java()
            which.assert_not_called()

    def test_windows_studio_jbr_discovery_uses_exe_and_sets_environment_for_children(self):
        java_home = self.root / "Programs/Android/Android Studio/jbr"
        self.binary(java_home / "bin/java.exe")
        self.binary(java_home / "bin/javac.exe")
        with patch.object(tv.sys, "platform", "win32"), \
                patch.dict(os.environ, {"ProgramFiles": str(self.root / "Programs")}), \
                patch.object(tv.shutil, "which", return_value=None), \
                patch.object(tv.subprocess, "run", return_value=result(stderr='openjdk version "21.0.8"')) as process, \
                patch.object(tv, "require_sdk", return_value=self.root / "sdk"):
            env = tv.build_environment()
            self.assertEqual(env["JAVA_HOME"], str(java_home))
            self.assertEqual(env["ANDROID_HOME"], env["ANDROID_SDK_ROOT"])
            self.assertTrue(env["PATH"].startswith(str(java_home / "bin")))
            self.assertEqual(process.call_args.args[0], [str(java_home / "bin/java.exe"), "-version"])

    def test_java_version_outside_wrapper_support_is_actionable(self):
        java_home = self.root / "jdk"
        self.binary(java_home / "bin" / tv.executable_name("java"))
        self.binary(java_home / "bin" / tv.executable_name("javac"))
        with patch.dict(os.environ, {"JAVA_HOME": str(java_home)}), \
                patch.object(tv.subprocess, "run", return_value=result(stderr='openjdk version "11.0.20"')) as process:
            with self.assertRaisesRegex(tv.ToolError, "推荐 JDK 17 或 21"):
                tv.require_java()
            process.assert_called_once()

    def test_find_existing_venv_ffmpeg_without_importing_or_downloading(self):
        for platform, packages in (("linux", "lib/python3.12/site-packages"), ("win32", "Lib/site-packages")):
            with self.subTest(platform=platform), patch.object(tv.sys, "platform", platform), \
                    patch.object(tv.shutil, "which", return_value=None), patch.object(tv.sys, "prefix", str(self.root / "unused")):
                binary = self.binary(self.root / ".venv" / packages / "static_ffmpeg/bin" / platform / tv.executable_name("ffmpeg"))
                self.assertEqual(tv.find_ffmpeg(), str(binary))
                with self.assertRaisesRegex(tv.ToolError, "路径不可执行"):
                    tv.find_ffmpeg(self.root / "missing")


class CommandTests(ContextTestCase):
    def setUp(self):
        self.enter_context(contextlib.redirect_stdout(io.StringIO()))

    def test_build_test_and_check_route_to_only_the_required_gradle_tasks(self):
        cases = {
            "build": ([":app:assembleDebug"], False),
            "test": ([":app:testDebugUnitTest", ":app:lintDebug"], True),
            "check": ([":app:testDebugUnitTest", ":app:lintDebug", ":app:assembleDebug", ":app:assembleRelease"], True),
        }
        for command, (tasks, tests) in cases.items():
            with self.subTest(command=command), patch.object(tv, "build_environment", return_value={"JAVA_HOME": "jdk"}), \
                    patch.object(tv, "tool_tests") as tools, patch.object(tv, "gradle") as gradle:
                tv.main([command, "--offline"])
                gradle.assert_called_once_with(tasks, env={"JAVA_HOME": "jdk"}, offline=True)
                self.assertEqual(tools.called, tests)

    def test_test_pipeline_checks_python_tools_and_documentation_links(self):
        with patch.object(tv, "run") as run:
            tv.tool_tests()
        self.assertIn("unittest", run.call_args_list[0].args[0])
        self.assertEqual(run.call_args_list[1].args[0][1:],
                         [tv.PROJECT.parent / "scripts/check_docs_links.py", "--root", "android-tv"])
        self.assertEqual(run.call_args_list[1].kwargs["cwd"], tv.PROJECT.parent)

    def test_gradle_uses_platform_wrapper_and_an_explicit_project_directory(self):
        for platform, wrapper in (("linux", "gradlew"), ("win32", "gradlew.bat")):
            with self.subTest(platform=platform), patch.object(tv.sys, "platform", platform), \
                    patch.object(tv.subprocess, "run", return_value=result()) as process:
                tv.gradle([":app:assembleDebug"], env={"sample": "value"}, offline=True)
                self.assertEqual(process.call_args.args[0], [str(tv.PROJECT / wrapper), "--offline", ":app:assembleDebug"])
                self.assertEqual(process.call_args.kwargs["cwd"], tv.PROJECT)
                self.assertEqual(process.call_args.kwargs["env"], {"sample": "value"})

    def test_package_delegates_to_existing_export_rules_with_environment(self):
        with patch.object(tv, "build_environment", return_value={"JAVA_HOME": "jdk"}), patch.object(tv, "run") as run:
            tv.main(["package", "release", "--offline"])
        run.assert_called_once_with([tv.sys.executable, tv.TOOLS / "package_apk.py", "release", "--offline"], env={"JAVA_HOME": "jdk"})

    def test_old_package_entrypoint_uses_windows_wrapper(self):
        artifact = Path("jzmedia-tv-0.5.1-debug.apk")
        with patch.object(package_apk, "os", SimpleNamespace(name="nt")), \
                patch.object(tv.sys, "argv", ["package_apk.py", "debug"]), \
                patch.object(package_apk, "read_version", return_value=("0.5.1", 7)), \
                patch.object(package_apk, "resolve_revision", return_value={"commit": None, "dirty": None}), \
                patch.object(package_apk, "export_apk", return_value=artifact), \
                patch.object(package_apk.subprocess, "run") as run:
            package_apk.main()
        self.assertEqual(run.call_args.args[0][0], str(package_apk.PROJECT / "gradlew.bat"))

    def test_device_helpers_do_not_require_java_and_pair_does_not_capture_a_code(self):
        with patch.object(tv, "find_adb", return_value="/sdk/adb"), \
                patch.object(tv, "build_environment") as environment, patch.object(tv, "run", return_value=result()) as run:
            tv.main(["devices"])
            run.assert_called_with(["/sdk/adb", "devices", "-l"])
            tv.main(["pair", "192.168.1.2:37777"])
            run.assert_called_with(["/sdk/adb", "pair", "192.168.1.2:37777"])
            environment.assert_not_called()

    def test_adb_connect_failure_is_reported_even_when_adb_exits_zero(self):
        with patch.object(tv, "find_adb", return_value="adb"), \
                patch.object(tv, "run", return_value=result("failed to connect: Connection refused")):
            with self.assertRaisesRegex(tv.ToolError, "调试地址和端口"):
                tv.main(["connect", "192.168.1.2:5555"])


class DeviceTests(ContextTestCase):
    def setUp(self):
        self.enter_context(contextlib.redirect_stdout(io.StringIO()))

    def test_missing_unauthorized_offline_and_multiple_devices_fail_with_next_steps(self):
        cases = (("", "未发现设备"), ("TV unauthorized", "允许此电脑"),
                 ("TV offline", "重新连接"), ("TV device\nTV2 device", "--serial"),
                 ("TV device\nTV2 unauthorized", "--serial"))
        for devices, hint in cases:
            with self.subTest(devices=devices), patch.object(tv, "run", return_value=result("List of devices attached\n" + devices)):
                with self.assertRaisesRegex(tv.ToolError, hint):
                    tv.choose_device("adb")

    def test_explicit_serial_selects_exact_device_and_unknown_serial_fails(self):
        with patch.object(tv, "run", return_value=result("List of devices attached\nTV device\nTV2 device\n")):
            self.assertEqual(tv.choose_device("adb", "TV2"), "TV2")
            with self.assertRaisesRegex(tv.ToolError, "未找到设备 TV3"):
                tv.choose_device("adb", "TV3")

    def test_install_rejects_device_ambiguity_before_building(self):
        with patch.object(tv, "find_adb", return_value="adb"), \
                patch.object(tv, "run", return_value=result("List of devices attached\nTV device\nTV2 device\n")), \
                patch.object(tv, "gradle") as gradle:
            with self.assertRaisesRegex(tv.ToolError, "--serial"):
                tv.main(["install"])
            gradle.assert_not_called()

    def test_install_builds_then_launches_only_after_success(self):
        with patch.object(tv, "find_adb", return_value="adb"), patch.object(tv, "choose_device", return_value="TV"), \
                patch.object(tv, "build_environment", return_value={}), patch.object(tv, "gradle") as gradle, \
                patch.object(tv.Path, "is_file", return_value=True), \
                patch.object(tv, "run", side_effect=[result("Success\n"), result("Status: ok\n")]) as run:
            tv.main(["install", "--serial", "TV"])
            gradle.assert_called_once_with([":app:assembleDebug"], env={}, offline=False)
            self.assertEqual(run.call_args_list[0].args[0], ["adb", "-s", "TV", "install", "-r", tv.DEBUG_APK])
            self.assertEqual(run.call_args_list[1].args[0], ["adb", "-s", "TV", "shell", "am", "start", "-W", "-n", tv.DEBUG_ACTIVITY])

    def test_failed_install_never_uninstalls_downgrades_or_launches(self):
        for response in (result("Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE]"), tv.ToolError("VERSION_DOWNGRADE")):
            with self.subTest(response=response), patch.object(tv, "find_adb", return_value="adb"), \
                    patch.object(tv, "choose_device", return_value="TV"), patch.object(tv, "build_environment", return_value={}), \
                    patch.object(tv, "gradle"), patch.object(tv.Path, "is_file", return_value=True), \
                    patch.object(tv, "run", side_effect=[response]) as run:
                with self.assertRaisesRegex(tv.ToolError, "不会自动卸载或降级"):
                    tv.main(["install"])
                self.assertEqual(run.call_count, 1)
                self.assertEqual(run.call_args.args[0], ["adb", "-s", "TV", "install", "-r", tv.DEBUG_APK])

    def test_existing_apk_installs_without_jdk_build_or_guessing_its_launch_activity(self):
        with tempfile.TemporaryDirectory(prefix="jzmedia-existing-apk-") as directory:
            apk = Path(directory).resolve() / "signed-release.apk"
            apk.write_bytes(b"fake APK")
            with patch.object(tv, "find_adb", return_value="adb"), patch.object(tv, "choose_device", return_value="TV"), \
                    patch.object(tv, "build_environment") as environment, patch.object(tv, "gradle") as gradle, \
                    patch.object(tv, "run", return_value=result("Success")) as run:
                tv.main(["install", "--apk", str(apk)])
                run.assert_called_once_with(["adb", "-s", "TV", "install", "-r", apk], capture=True)
                environment.assert_not_called()
                gradle.assert_not_called()

    def test_missing_existing_apk_fails_before_connecting_to_a_device(self):
        with tempfile.TemporaryDirectory(prefix="jzmedia-missing-apk-") as directory, patch.object(tv, "find_adb") as adb:
            with self.assertRaisesRegex(tv.ToolError, "--apk 需要指向"):
                tv.main(["install", "--apk", str(Path(directory) / "missing.apk")])
            adb.assert_not_called()

    def test_launch_error_is_reported_as_installed_but_not_started(self):
        with patch.object(tv, "find_adb", return_value="adb"), patch.object(tv, "choose_device", return_value="TV"), \
                patch.object(tv, "build_environment", return_value={}), patch.object(tv, "gradle"), \
                patch.object(tv.Path, "is_file", return_value=True), \
                patch.object(tv, "run", side_effect=[result("Success"), result("Error: Activity not found")]):
            with self.assertRaisesRegex(tv.ToolError, "已安装，但启动失败"):
                tv.main(["install"])


class DemoTests(ContextTestCase):
    def setUp(self):
        self.enter_context(contextlib.redirect_stdout(io.StringIO()))
        self.enter_context(patch.object(tv, "find_adb", return_value="adb"))
        self.enter_context(patch.object(tv, "choose_device", return_value="TV"))
        self.enter_context(patch.object(tv, "find_ffmpeg", return_value="/ffmpeg"))

    def test_normal_demo_passes_fixture_flags_and_cleans_only_its_port(self):
        with patch.object(tv, "run", return_value=result()) as run:
            tv.main(["demo", "--port", "18889", "--hls", "--require-token", "--browse-stress", "--season-stress", "--no-show-poster", "--card-stress"])
        commands = [call.args[0] for call in run.call_args_list]
        self.assertEqual(commands[1], ["adb", "-s", "TV", "reverse", "--no-rebind", "tcp:18889", "tcp:18889"])
        self.assertEqual(commands[2], [tv.sys.executable, tv.TOOLS / "smoke_server.py", "--port", "18889", "--ffmpeg", "/ffmpeg",
                                       "--hls", "--require-token", "--browse-stress", "--season-stress", "--no-show-poster", "--card-stress"])
        self.assertEqual(commands[3], ["adb", "-s", "TV", "reverse", "--remove", "tcp:18889"])

    def test_server_failure_and_keyboard_interrupt_both_remove_the_forward(self):
        for failure in (tv.ToolError("server failed"), KeyboardInterrupt()):
            with self.subTest(failure=type(failure)), patch.object(tv, "run", side_effect=[result(), result(), failure, result()]) as run:
                with self.assertRaises(type(failure)):
                    tv.main(["demo"])
                self.assertEqual(run.call_args.args[0], ["adb", "-s", "TV", "reverse", "--remove", "tcp:18888"])

    def test_existing_forward_is_not_overwritten_or_removed(self):
        with patch.object(tv, "run", return_value=result("TV tcp:18888 tcp:12345\n")) as run:
            with self.assertRaisesRegex(tv.ToolError, "已有|已被转发占用"):
                tv.main(["demo"])
        self.assertEqual(run.call_count, 1)

    def test_failed_forward_creation_does_not_remove_other_mappings(self):
        with patch.object(tv, "run", side_effect=[result(), tv.ToolError("cannot bind")]) as run:
            with self.assertRaisesRegex(tv.ToolError, "cannot bind"):
                tv.main(["demo"])
        self.assertEqual(run.call_count, 2)

    def test_cleanup_failure_preserves_original_error_and_shows_recovery_command(self):
        errors = io.StringIO()
        with contextlib.redirect_stderr(errors), \
                patch.object(tv, "run", side_effect=[result(), result(), tv.ToolError("server failed"), tv.ToolError("offline")]):
            with self.assertRaisesRegex(tv.ToolError, "server failed"):
                tv.main(["demo"])
        self.assertIn("adb -s TV reverse --remove tcp:18888", errors.getvalue())


if __name__ == "__main__":
    unittest.main(verbosity=2)
