#!/usr/bin/env python3
"""Generate all platform design artifacts from repository-owned SVG masters.

No third-party dependencies for vectors, tokens, inventory and normal --check.
Use --render-brand for deterministic PNG/ICO exports (design/requirements-render.txt).
"""
from __future__ import annotations

import argparse
import hashlib
import html
from html.parser import HTMLParser
import io
import inspect
import json
from pathlib import Path
import re
import struct
import sys
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
DESIGN = ROOT / 'design'
NS = '{http://www.w3.org/2000/svg}'
GENERATOR_VERSION = 1
GENERATED = '// Generated by scripts/build_design.py. Edit design/ masters, not this file.\n'
TAG_RE = re.compile(r'<(?P<tag>[A-Za-z][\w.-]*)\b(?P<attrs>(?:"[^"]*"|\'[^\']*\'|[^\'">])*)>', re.S)
ATTR_RE = re.compile(r'([:@\w.-]+)\s*=\s*(?:"([^"]*)"|\'([^\']*)\')')


def json_text(value):
    return json.dumps(value, ensure_ascii=False, indent=2) + '\n'


def read_json(name):
    return json.loads((DESIGN / name).read_text())


def icon_paths(asset):
    path = ROOT / asset['master']
    svg = ET.parse(path).getroot()
    if svg.attrib.get('viewBox') != '0 0 24 24':
        raise ValueError(f'{path}: icon must have a 24-unit viewBox')
    if asset['grid'] != [24, 24]:
        raise ValueError(f'{path}: manifest grid must match the icon viewBox')
    allowed_root = {'viewBox', 'fill', 'stroke', 'stroke-width', 'stroke-linecap', 'stroke-linejoin'}
    if set(svg.attrib) - allowed_root or svg.attrib.get('fill') != 'none' or svg.attrib.get('stroke') != 'currentColor':
        raise ValueError(f'{path}: icon root may only define the portable monochrome contract')
    for key, value in [('stroke-width', '1.7'), ('stroke-linecap', 'round'), ('stroke-linejoin', 'round')]:
        if svg.attrib.get(key) != value:
            raise ValueError(f'{path}: expected {key}={value}')
    paths = []
    for node in svg:
        if node.tag != NS + 'path' or set(node.attrib) - {'d', 'fill', 'stroke', 'fill-rule'}:
            raise ValueError(f'{path}: only portable paths, fill/stroke and fill-rule allowed')
        if any(node.attrib.get(key, default) not in ('none', 'currentColor') for key, default in [('fill', 'none'), ('stroke', 'currentColor')]):
            raise ValueError(f'{path}: functional fill/stroke must be none or currentColor on every platform')
        if node.attrib.get('fill-rule', 'nonzero') not in ('nonzero', 'evenodd'):
            raise ValueError(f'{path}: unsupported fill-rule')
        paths.append({'d': node.attrib['d'], 'fill': node.attrib.get('fill', 'none'),
                      'stroke': node.attrib.get('stroke', 'currentColor'),
                      'fillRule': node.attrib.get('fill-rule', 'nonzero')})
    return paths


def aliases_for(manifest, family):
    return {**manifest['aliases']['app'], **manifest['aliases'].get(family, {})}


def canonical(name, manifest, family='app'):
    return aliases_for(manifest, family).get(name, name)


def web_icons(registry, manifest):
    return (GENERATED + 'export const iconRegistry = ' + json_text(registry).rstrip() + '\n'
            + '\n'.join(f'export const {family}IconAliases = {json.dumps(aliases_for(manifest, family), ensure_ascii=False)}'
                        for family in ('app', 'player', 'tv'))
            + '\nexport function resolveIcon(name, family = \'app\') {\n'
            + "  const aliases = family === 'player' ? playerIconAliases : family === 'tv' ? tvIconAliases : appIconAliases\n"
            + "  return iconRegistry[aliases[name] || name] || iconRegistry[family === 'player' ? 'info' : 'warning']\n}\n")


def kotlin_icons(registry, manifest):
    text = GENERATED + '''package org.jzmedia.tv.ui.generated

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp

object DesignIcons {
    private data class Shape(val d: String, val fill: Boolean = false, val stroke: Boolean = true, val evenOdd: Boolean = false)
    private val paths = mapOf(
'''
    for name, shapes in registry.items():
        entries = ', '.join('Shape(' + json.dumps(s['d']) +
                            f', fill = {str(s["fill"] != "none").lower()}, stroke = {str(s["stroke"] != "none").lower()}, evenOdd = {str(s["fillRule"] == "evenodd").lower()})'
                            for s in shapes)
        text += f'        "{name}" to listOf({entries}),\n'
    text += '    )\n    private val aliases = mapOf(\n'
    for alias, name in aliases_for(manifest, 'tv').items():
        text += f'        "{alias}" to "{name}",\n'
    text += '''    )
    private val icons: Map<String, ImageVector> by lazy {
        paths.mapValues { (name, shapes) ->
            ImageVector.Builder(name = "jzmedia-$name", defaultWidth = 24.dp, defaultHeight = 24.dp,
                viewportWidth = 24f, viewportHeight = 24f).apply {
                shapes.forEach { shape ->
                    addPath(pathData = PathParser().parsePathString(shape.d).toNodes(),
                        fill = if (shape.fill) SolidColor(Color.White) else null,
                        stroke = if (shape.stroke) SolidColor(Color.White) else null,
                        pathFillType = if (shape.evenOdd) PathFillType.EvenOdd else PathFillType.NonZero,
                        strokeLineWidth = 1.7f, strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round)
                }
            }.build()
        }
    }
    fun get(name: String): ImageVector = icons.getValue(aliases[name] ?: name)
    val names: Set<String> get() = paths.keys
}
'''
    return text


def token_outputs(tokens):
    css = '/* Generated by scripts/build_design.py from design/tokens.json. */\n:root {\n'
    css += ''.join(f'  {key}: {value};\n' for key, value in tokens['web'].items()) + '}\n'
    kt = GENERATED + '''package org.jzmedia.tv.ui.generated

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object DesignTokens {
'''
    for key, reference in tokens['android']['colors'].items():
        value = tokens['web'][reference['token']]
        if not re.fullmatch(r'#[0-9a-fA-F]{3}(?:[0-9a-fA-F]{3})?',value):raise ValueError(f'Android color {key} must reference an opaque hex semantic token')
        digits=value[1:]
        if len(digits)==3:digits=''.join(character*2 for character in digits)
        kt += f'    val {key} = Color(0xFF{digits.upper()})\n'
    for key, value in tokens['android']['dimensions'].items():
        kt += f'    val {key} = {value}.dp\n'
    for key, value in tokens['android']['scalars'].items():
        kt += f'    const val {key} = {value}f\n'
    return css, kt + '}\n'


def brand_outputs(manifest=None):
    assets = {asset['id']: asset for asset in (manifest or read_json('assets.json'))['assets']}
    exports = []
    def add(path, asset, fmt, dimensions, density='1x', transparent=True, safe_area=None, sources=None):
        sources = sources or [asset]
        exports.append({'path': path, 'asset': asset, 'format': fmt, 'dimensions': dimensions,
                        'units': 'viewBox' if fmt in ('svg', 'android-vector') else 'px',
                        'density': density, 'transparent': transparent, 'safe_area': safe_area or '保留母版内边距',
                        'generator_version': GENERATOR_VERSION, 'master_revision': assets[asset]['revision'],
                        'source_assets': sources, 'source_revisions': {name: assets[name]['revision'] for name in sources}})
    for folder in ['frontend/public', 'docs/assets/design']:
        # Browsers may prefer SVG even on 1x displays; use the small optical master.
        add(folder + '/favicon.svg', 'brand-favicon-16', 'svg', assets['brand-favicon-16']['grid'], 'vector')
        add(folder + '/logo.svg', 'brand-wordmark', 'svg', assets['brand-wordmark']['grid'], 'vector')
        for size in [16, 32, 48]:
            add(f'{folder}/favicon-{size}x{size}.png', f'brand-favicon-{size}' if size != 48 else 'brand-mark', 'png', [size, size])
        add(folder + '/favicon.ico', 'brand-mark', 'ico', [[16, 16], [32, 32], [48, 48]], 'multi-size',
            sources=['brand-favicon-16', 'brand-favicon-32', 'brand-mark'])
    add('frontend/public/apple-touch-icon.png', 'brand-mark', 'png', [180, 180])
    add('frontend/public/icon-512.png', 'brand-mark', 'png', [512, 512])
    add('android-tv/app/src/main/res/drawable/ic_launcher.xml', 'brand-mark', 'android-vector', assets['brand-mark']['grid'], 'vector')
    add('android-tv/app/src/main/res/drawable/jz_wordmark.xml', 'brand-wordmark', 'android-vector', assets['brand-wordmark']['grid'], 'vector')
    exports[-1]['default_dp'] = [106, 32]
    add('android-tv/app/src/main/res/drawable-xhdpi/tv_banner.png', 'brand-wordmark', 'png', [320, 180], 'xhdpi (160×90dp)', False, '居中组合宽240px，四周至少40px')
    return exports


def brand_vector_outputs(exports, manifest):
    assets = {a['id']: a for a in manifest['assets']}
    outputs = {}
    for asset in assets.values():
        if asset['category'] != 'brand':
            continue
        root = ET.parse(ROOT / asset['master']).getroot()
        expected = '0 0 ' + ' '.join(map(str, asset['grid']))
        if root.attrib.get('viewBox') != expected:
            raise ValueError(f'{asset["master"]}: brand viewBox differs from declared grid')
        for node in root:
            if node.tag != NS + 'path' or set(node.attrib) - {'d', 'fill', 'stroke', 'stroke-width', 'stroke-linecap', 'stroke-linejoin', 'fill-rule'}:
                raise ValueError(f'{asset["master"]}: brand master must contain portable outline paths')
    for spec in exports:
        if spec['format'] == 'svg':
            outputs[spec['path']] = (ROOT / assets[spec['asset']]['master']).read_bytes()
        elif spec['format'] == 'android-vector':
            root = ET.parse(ROOT / assets[spec['asset']]['master']).getroot()
            content = '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by scripts/build_design.py. -->\n'
            width, height = spec['dimensions']
            default_width, default_height = spec.get('default_dp', [width, height])
            content += f'<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="{default_width}dp" android:height="{default_height}dp" android:viewportWidth="{width}" android:viewportHeight="{height}">\n'
            mapping = {'d': 'pathData', 'fill': 'fillColor', 'stroke': 'strokeColor',
                       'stroke-width': 'strokeWidth', 'stroke-linecap': 'strokeLineCap', 'stroke-linejoin': 'strokeLineJoin', 'fill-rule': 'fillType'}
            for path in root:
                attrs = []
                for key, value in path.attrib.items():
                    if key in mapping:
                        if value == 'none': value = '#00000000'
                        if key == 'fill-rule': value = 'evenOdd' if value == 'evenodd' else 'nonZero'
                        attrs.append(f'android:{mapping[key]}="{value}"')
                content += '    <path ' + ' '.join(attrs) + ' />\n'
            outputs[spec['path']] = content + '</vector>\n'
    return outputs


def render_brand(exports, manifest):
    import cairosvg
    from PIL import Image
    assets = {a['id']: a for a in manifest['assets']}
    outputs = {}
    cache = {}
    def png(asset_id, width, height):
        key = (asset_id, width, height)
        if key not in cache:
            cache[key] = cairosvg.svg2png(url=str(ROOT / assets[asset_id]['master']), output_width=width, output_height=height)
        return cache[key]
    for spec in exports:
        if spec['format'] == 'png':
            width, height = spec['dimensions']
            if spec['path'].endswith('tv_banner.png'):
                mark = Image.open(io.BytesIO(png('brand-wordmark', 240, 72))).convert('RGBA')
                canvas = Image.new('RGBA', (width, height), '#141414')
                canvas.alpha_composite(mark, ((width - mark.width) // 2, (height - mark.height) // 2))
                buf = io.BytesIO(); canvas.convert('RGB').save(buf, format='PNG'); content = buf.getvalue()
            else:
                content = png(spec['asset'], width, height)
            outputs[spec['path']] = content
        elif spec['format'] == 'ico':
            # Explicit frames preserve each optical master; Pillow's 32px source cannot invent a 48px frame.
            frames = [png('brand-favicon-16', 16, 16), png('brand-favicon-32', 32, 32), png('brand-mark', 48, 48)]
            offset = 6 + len(frames) * 16
            entries = []
            for size, frame in zip((16, 32, 48), frames):
                entries.append(struct.pack('<BBBBHHII', size, size, 0, 0, 1, 32, len(frame), offset))
                offset += len(frame)
            outputs[spec['path']] = struct.pack('<HHH', 0, 1, 3) + b''.join(entries) + b''.join(frames)
    return outputs


def validate_rasters(exports):
    errors = []
    for spec in exports:
        if spec['format'] not in ('png', 'ico'): continue
        path = ROOT / spec['path']
        if not path.exists():
            errors.append(f'{spec["path"]}: missing; run with --render-brand'); continue
        data = path.read_bytes()
        if spec['format'] == 'png':
            dims = list(struct.unpack('>II', data[16:24])) if data[:8] == b'\x89PNG\r\n\x1a\n' else None
            if dims != spec['dimensions']: errors.append(f'{spec["path"]}: wrong PNG dimensions {dims}')
        else:
            if len(data) < 6 or struct.unpack('<HH', data[:4]) != (0, 1):
                errors.append(f'{spec["path"]}: invalid ICO'); continue
            count = struct.unpack('<H', data[4:6])[0]
            dimensions = []
            for i in range(count):
                w,h,_,_,_,_,size,offset = struct.unpack('<BBBBHHII', data[6+i*16:22+i*16])
                w,h = w or 256,h or 256
                frame = data[offset:offset+size]
                actual = tuple(struct.unpack('>II',frame[16:24])) if frame[:8] == b'\x89PNG\r\n\x1a\n' else None
                if actual != (w,h): errors.append(f'{spec["path"]}: ICO entry differs from actual pixel layer')
                dimensions.append([w,h])
            if dimensions != spec['dimensions']: errors.append(f'{spec["path"]}: incomplete ICO sizes {dimensions}')
    return errors


def compact(value, max_len=180):
    return re.sub(r'\s+', ' ', value).strip()[:max_len]


def source_files():
    return sorted([*ROOT.glob('frontend/src/**/*.vue'), *ROOT.glob('android-tv/app/src/main/java/**/*.kt')])


def source_family(path):
    name = path.stem.lower()
    groups = [('播放', ('player','subtitle','playback','seekbar','preview')), ('媒体管理', ('library','libraries','scan','organize','upload','file','fsbrowser','binding','pending')),
              ('设置与引导', ('setting','setup','onboard','connection','metadata','ai')), ('浏览与资料', ('browse','detail','movie','tv','episode','season','collection','person','cast','rating'))]
    for label, words in groups:
        if any(word in name for word in words): return label
    return '通用控件与导航'

FUNCTION_GLYPHS = set('★☆♥❤⟳↻✕✖✗✔✓⚠⌕⚙☰▶►◀◄⏪⏩⏸⏹⌂⇩⇧⇪🔍📂📁🎬📺🗑🖉✎♢✚＋←→↑↓')
TAG_ALIASES = {'app-icon': 'AppIcon', 'player-icon': 'PlayerIcon', 'jz-button': 'JzButton',
               'artwork-placeholder': 'ArtworkPlaceholder', 'router-link': 'RouterLink', 'spinner': 'Spinner'}


def decode_ui_symbols(text):
    """Decode source forms that produce a single visible symbol, preserving ordinary CJK."""
    text = html.unescape(text)
    patterns = [r'(?<!\\)\\u\{([0-9a-fA-F]{1,6})\}', r'(?<!\\)\\U([0-9a-fA-F]{8})',
                r'(?<!\\)\\u([0-9a-fA-F]{4})', r'(?<!\\)\\([0-9a-fA-F]{1,6})(?:\s|(?=["\']))']
    for pattern in patterns:
        text = re.sub(pattern, lambda m: chr(int(m[1], 16)) if int(m[1], 16) <= 0x10FFFF else m[0], text)
    return text


def functional_glyph(character):
    point = ord(character)
    return character in FUNCTION_GLYPHS or any(start <= point <= end for start, end in (
        (0x2190, 0x21FF), (0x2300, 0x23FF), (0x25A0, 0x27FF),
        (0x1F000, 0x1FAFF), (0xE000, 0xF8FF),
    ))


def expression_values(expression):
    """Return all literal ternary leaves, or None when any output needs a contract.

    Conditions are opaque; a literal in a condition is never an icon reference.
    Partial literal extraction would miss `condition ? 'play' : dynamicName`.
    """
    expression = expression.strip()
    literal = re.fullmatch(r'''"((?:\\.|[^"\\])*)"|'((?:\\.|[^'\\])*)' ''', expression, re.X)
    if literal:
        return [decode_ui_symbols(literal[1] if literal[1] is not None else literal[2])]
    quote = None
    escaped = False
    depth = 0
    question = None
    pending = 0
    for index, char in enumerate(expression):
        if escaped:
            escaped = False
        elif quote:
            if char == '\\': escaped = True
            elif char == quote: quote = None
        elif char in ('"', "'", '`'):
            quote = char
        elif char in '([{': depth += 1
        elif char in ')]}': depth -= 1
        elif depth == 0 and char == '?' and expression[index:index+2] not in ('?.', '??') and expression[index-1:index] != '?':
            if question is None: question = index
            pending += 1
        elif depth == 0 and char == ':' and question is not None:
            pending -= 1
            if pending == 0:
                left = expression_values(expression[question+1:index])
                right = expression_values(expression[index+1:])
                return left + right if left is not None and right is not None else None
    if expression.startswith('(') and expression.endswith(')'):
        return expression_values(expression[1:-1])
    return None


def kotlin_expression_values(expression):
    expression = expression.strip()
    if expression.startswith('"'):
        return expression_values(expression)
    prefix = re.match(r'if\s*\(', expression)
    if not prefix: return None
    depth = 1
    quote = False
    escaped = False
    end = prefix.end()
    while end < len(expression) and depth:
        char = expression[end]
        if escaped: escaped = False
        elif char == '\\' and quote: escaped = True
        elif char == '"': quote = not quote
        elif not quote:
            if char == '(': depth += 1
            elif char == ')': depth -= 1
        end += 1
    branches = re.fullmatch(r'\s*("(?:\\.|[^"\\])*")\s+else\s+(.+)', expression[end:], re.S)
    if not branches: return None
    left = expression_values(branches[1])
    right = kotlin_expression_values(branches[2])
    return left + right if left is not None and right is not None else None


def icon_property_values(text, is_vue=False):
    values, unresolved = [], []
    text = without_comments(text, is_vue)
    for match in re.finditer(r'''(?:\bicon|['"]icon['"])\s*:\s*''', text):
        value = re.match(r'''"((?:\\.|[^"\\])*)"|'((?:\\.|[^'\\])*)' ''', text[match.end():], re.X)
        if value:
            values.append(decode_ui_symbols(value[1] if value[1] is not None else value[2]))
        else:
            unresolved.append(compact(text[match.end():match.end()+80]))
    return values, unresolved


def without_comments(text, is_vue=False):
    def strip_code(code):
        result = list(code)
        index, quote = 0, None
        while index < len(code):
            char = code[index]
            if quote:
                if char == '\\': index += 2; continue
                if char == quote: quote = None
            elif char in ('"', "'", '`'):
                quote = char
            elif code[index:index+2] in ('//', '/*'):
                if code[index:index+2] == '//':
                    end = code.find('\n', index)
                    if end < 0: end = len(code)
                else:
                    end = code.find('*/', index+2)
                    end = len(code) if end < 0 else end+2
                result[index:end] = ['\n' if c == '\n' else ' ' for c in code[index:end]]
                index = end
                continue
            index += 1
        return ''.join(result)
    if not is_vue:
        return strip_code(text)

    # Vue text and attribute values may literally contain "//". Only script/style
    # data uses code comments; HTMLParser also preserves comment-looking attribute text.
    class SourceComments(HTMLParser):
        def __init__(self):
            super().__init__(convert_charrefs=False)
            self.mode = None
            self.replacements = []
            self.offsets = [0]
            for match in re.finditer('\n', text): self.offsets.append(match.end())

        def source_offset(self):
            line, column = self.getpos()
            return self.offsets[line-1] + column

        def handle_starttag(self, tag, attrs):
            if tag in ('script', 'style'): self.mode = tag

        def handle_endtag(self, tag):
            if tag == self.mode: self.mode = None

        def handle_data(self, data):
            if self.mode:
                start = self.source_offset()
                self.replacements.append((start, start+len(data), strip_code(data)))

        def handle_comment(self, data):
            start = self.source_offset()
            end = text.find('-->', start) + 3
            self.replacements.append((start, end, ''.join('\n' if c == '\n' else ' ' for c in text[start:end])))

    parser = SourceComments()
    parser.feed(text)
    for start, end, replacement in reversed(parser.replacements): text = text[:start] + replacement + text[end:]
    return text


def glyph_errors(contracts):
    errors = []
    exceptions = contracts.get('text_symbols', [])
    paths = sorted([*ROOT.glob('frontend/src/**/*.vue'), *ROOT.glob('frontend/src/**/*.js'),
                    *ROOT.glob('frontend/src/**/*.css'), *ROOT.glob('android-tv/app/src/main/java/**/*.kt')])
    for path in paths:
        rel = path.relative_to(ROOT).as_posix()
        if '/generated/' in rel: continue
        for number, line in enumerate(without_comments(path.read_text(), path.suffix == '.vue').splitlines(), 1):
            line = decode_ui_symbols(line)
            for symbol in filter(functional_glyph, set(line)):
                if not any(e['source'] == rel and symbol in e['symbols'] and
                           any(context in line for context in e['contexts']) for e in exceptions):
                    errors.append(f'{rel}:{number}: unregistered UI glyph {symbol!r}; use an icon or document this text context')
    return errors


def css_geometry_index():
    rules = []
    for path in sorted([*ROOT.glob('frontend/src/**/*.vue'), *ROOT.glob('frontend/src/**/*.css')]):
        text = path.read_text()
        if path.suffix == '.vue':
            style = re.search(r'<style\b[^>]*>([\s\S]*?)</style>', text)
            if not style: continue
            offset = style.start(1); body = style[1]
        else: offset = 0; body = text
        for match in re.finditer(r'([^{}]+)\{([^{}]*)\}', body):
            geometry = re.findall(r'(?<![-\w])((?:min-|max-)?(?:width|height)|padding(?:-[\w]+)?|gap|font-size|aspect-ratio)\s*:\s*([^;{}]+)', match[2])
            if geometry:
                rules.append({'source':path.relative_to(ROOT).as_posix(), 'line':text[:offset+match.start()].count('\n')+1,
                              'selector':compact(match[1],240),'values':dict(geometry)})
    return rules


def web_geometry(tag, attrs, markup, source, rules, profiles):
    profile = 'web-icon' if tag in ('AppIcon','PlayerIcon','Spinner') else 'web-placeholder' if tag == 'ArtworkPlaceholder' else 'web-button' if tag == 'JzButton' else 'web-native' if tag in ('input','select','textarea','summary') else 'web-link' if tag in ('a','RouterLink','router-link') else 'web-specialized'
    explicit = attrs.get(':size') or attrs.get('size')
    icon_size = explicit or ('22' if tag == 'PlayerIcon' else '20' if tag == 'AppIcon' else '16' if tag == 'Spinner' else '32')
    classes = attrs.get('class','').split()
    classes += re.findall(r"'([a-z][\w-]+)'", attrs.get(':class',''))
    matches = [rule for rule in rules if (rule['source'] == source or rule['source'].endswith('.css'))
               and any(re.search(r'\.'+re.escape(name)+r'(?![\w-])',rule['selector']) for name in classes)]
    info = {'unit':'CSS px', 'profile':profile, 'specification':profiles[profile]['specification'],
            'measurement_status':'source specification; browser acceptance records actual geometry',
            'source': profiles[profile]['source'], 'overrides':matches}
    if profile == 'web-icon': info['value'] = icon_size
    elif profile == 'web-button':
        info['value'] = 'min-height:36px desktop / 44px touch' if attrs.get('size')=='compact' else 'min-height:40px desktop / 44px touch'
    elif profile == 'web-placeholder': info['value'] = '32px icon constrained by container max-width:40%; label retained'
    elif matches: info['value'] = ' / '.join(', '.join(f'{k}:{v}' for k,v in rule['values'].items()) for rule in matches)
    else: info['value'] = 'intrinsic text/form size; enclosing layout and profile determine geometry'
    return info


def tv_geometry(tag, args, source, profiles):
    if tag in ('TvIcon','TvNavIcon','TvLoading'): profile='tv-icon'
    elif tag=='TvAction': profile='tv-action'
    elif tag in ('Poster','TvPoster'): profile='tv-poster'
    elif tag in ('PosterCard','TvLandscapeCard'):profile='tv-poster-card'
    elif tag=='SearchHistoryAction': profile='tv-history'
    elif tag=='NavigationButton' or source.endswith('/TvNavigation.kt'):profile='tv-navigation'
    elif tag=='ActorCard' or source.endswith('/ActorScreens.kt'):profile='tv-actor'
    elif source.endswith('/EpisodeGrid.kt'):profile='tv-episode'
    elif source.endswith('/SearchScreen.kt'):profile='tv-keyboard' if 'keyHeight' in args else 'tv-history'
    elif source.endswith('/TvComponents.kt') and 'width(150.dp)' in args:profile='tv-poster-card'
    else:profile='tv-action'
    expressions=re.findall(r'\.(size|width|height|widthIn|heightIn|sizeIn|fillMaxWidth|weight)\(([^()]*)\)',args)
    spec=profiles[profile]
    return {'value':'; '.join(f'{name}({value})' for name,value in expressions) or spec['specification'],
            'unit':'dp','profile':profile,'specification':spec['specification'],'source':spec['source'],
            'modifier_expressions':[f'{name}({value})' for name,value in expressions],
            'measurement_status':'source specification; actual density and font scale belong in device acceptance'}


def inventory(manifest, registry, contracts):
    result = []
    errors = []
    profiles = read_json('platform-profiles.json')['profiles']
    geometry_rules = css_geometry_index()
    contract_map = {(c['source'], c['expression']): c for c in contracts['dynamic_icons']}
    native_map = {c['source']: c for c in contracts['specialized_controls']}
    vue_tags = {'JzButton','button','a','RouterLink','router-link','summary','input','select','textarea','AppIcon','PlayerIcon','Spinner','ArtworkPlaceholder','svg','img'}
    for path in source_files():
        rel = path.relative_to(ROOT).as_posix()
        if '/generated/' in rel: continue
        text = path.read_text()
        if path.suffix == '.vue':
            opening = re.search(r'<template\b[^>]*>', text)
            closing = text.rfind('</template>')
            template = ('\n' * text[:opening.start()].count('\n') + text[opening.start():closing+11]
                        if opening and closing >= opening.end() else '')
            for order, match in enumerate(TAG_RE.finditer(template)):
                raw_tag = match['tag']
                tag = TAG_ALIASES.get(raw_tag, raw_tag)
                if tag not in vue_tags: continue
                attrs = {re.sub(r'^v-bind:', ':', m[0]): html.unescape(m[1] or m[2]) for m in ATTR_RE.findall(match['attrs'])}
                line = template[:match.start()].count('\n')+1
                markup = match.group(0)
                end = template.find(f'</{raw_tag}>',match.end())
                inner = template[match.end():end] if end>=0 else ''
                if len(inner)>1600: inner=''
                caption = compact(re.sub(r'<[^>]+>',' ',inner))
                purpose = attrs.get('aria-label') or attrs.get(':aria-label') or attrs.get('title') or attrs.get(':title') or caption or tag
                asset_ids = []
                dynamic = None
                adapter = False
                family = 'player' if tag == 'PlayerIcon' else 'app'
                if tag in ('AppIcon','PlayerIcon'):
                    if 'v-bind' in attrs:
                        errors.append(f'{rel}:{line}: object v-bind on an icon needs an explicit name binding and contract')
                    if 'name' in attrs: asset_ids = [canonical(decode_ui_symbols(attrs['name']),manifest,family)]
                    elif ':name' in attrs:
                        dynamic=attrs[':name']; contract=contract_map.get((rel,dynamic))
                        literals=expression_values(dynamic)
                        if contract:
                            asset_ids=[canonical(n,manifest,family) for n in contract['assets']]
                            adapter = contract.get('adapter', False)
                        elif literals is not None: asset_ids=[canonical(n,manifest,family) for n in literals]
                        else: errors.append(f'{rel}:{line}: register dynamic icon expression {dynamic!r}')
                    elif 'v-bind' not in attrs:
                        errors.append(f'{rel}:{line}: icon has no registered name binding')
                elif tag=='Spinner': asset_ids=['loading']
                elif tag=='ArtworkPlaceholder':
                    kind=attrs.get('kind','poster')
                    asset_ids=[{'person':'person','collection':'collections'}.get(kind,'image')]
                    if ':kind' in attrs:
                        dynamic=attrs[':kind'];values=expression_values(dynamic)
                        if values is not None:asset_ids=list(dict.fromkeys({'person':'person','collection':'collections'}.get(value,'image') for value in values))
                        else:errors.append(f'{rel}:{line}: register dynamic placeholder kind {dynamic!r}')
                elif tag=='JzButton':
                    if 'v-bind' in attrs:
                        errors.append(f'{rel}:{line}: object v-bind on JzButton must expose an explicit icon binding for inventory')
                    if 'icon' in attrs: asset_ids=[canonical(decode_ui_symbols(attrs['icon']),manifest)] if attrs['icon'] else []
                    elif ':icon' in attrs:
                        dynamic=attrs[':icon'];contract=contract_map.get((rel,dynamic))
                        literals=expression_values(dynamic)
                        if contract:asset_ids=[canonical(n,manifest) for n in contract['assets']]
                        elif literals is not None:asset_ids=[canonical(n,manifest) for n in literals if n]
                        else:errors.append(f'{rel}:{line}: register dynamic button icon {dynamic!r}')
                elif tag=='img' and any('favicon' in a or 'logo.svg' in a for a in attrs.values()): asset_ids=['brand-wordmark' if any('logo.svg' in a for a in attrs.values()) else 'brand-favicon-16']
                if tag=='svg' and path.name not in ('AppIcon.vue','PlayerIcon.vue'):
                    errors.append(f'{rel}:{line}: inline business SVG must use a registered master')
                if tag in ('AppIcon','PlayerIcon','Spinner','ArtworkPlaceholder') and purpose == tag:
                    purpose = ' / '.join(a['name'] for a in manifest['assets'] if a['id'] in asset_ids) or '共享图标渲染器'
                for name in asset_ids:
                    if name not in registry and not (tag == 'img' and name in ('brand-favicon-16','brand-wordmark')):
                        errors.append(f'{rel}:{line}: unknown icon {name}')
                if tag=='button' and not any(selector in markup for selector in native_map.get(rel,{}).get('selectors',[])):
                    errors.append(f'{rel}:{line}: native button needs documented specialized control contract')
                category = 'asset' if tag in ('AppIcon','PlayerIcon','Spinner','ArtworkPlaceholder','svg') or (tag=='img' and asset_ids) else 'media-content' if tag=='img' and not asset_ids else 'link' if tag in ('a','RouterLink','router-link') else 'native-form' if tag in ('input','select','textarea','summary') else 'control'
                owner = 'decorative; surrounding control/text owns accessible name' if category=='asset' else attrs.get('aria-label') or attrs.get(':aria-label') or ('associated label / native form semantics' if category=='native-form' else 'visible text, title or enclosing media caption')
                states=['normal','focus','disabled'] if category in ('control','native-form','link') else ['normal']
                if ':loading' in attrs or ':disabled' in attrs: states+=['busy']
                if 'aria-pressed' in markup or 'aria-selected' in markup or ':class' in attrs: states+=['selected']
                for override in contracts.get('purpose_overrides',[]):
                    if override['source']==rel and set(asset_ids)&set(override['assets']):purpose=override['purpose']
                result.append({'id':f'{rel}:{tag}:{order}','source':rel,'line':line,'platforms':['web','mobile-web'],'category':category,'feature':source_family(path),'element':tag,'purpose':purpose,'assets':asset_ids,'dynamic_expression':dynamic,'display_size':web_geometry(tag, attrs, markup, rel, geometry_rules, profiles),'target':{'policy_touch_min_css_px':44,'measurement_status':'not inferred from source'} if category in ('control','native-form') else None,'states':states,'accessible_name_owner':owner,'classification':native_map.get(rel,{}).get('reason') if tag=='button' else 'media payload' if category=='media-content' else 'native control' if category=='native-form' else 'shared design component' if tag in ('AppIcon','PlayerIcon','JzButton','Spinner','ArtworkPlaceholder') else 'semantic link','source_excerpt':compact(markup)})
                if adapter:
                    result[-1]['purpose']=contract['reason']
                    result[-1]['category']='adapter'
                    result[-1]['supported_assets']=result[-1]['assets']
                    result[-1]['assets']=[]
        else:
            # Compose call sites and their icons are recorded even when button geometry remains native TV.
            pattern=r'\b(TvAction|TvIcon|TvNavIcon|TvPoster|TvLandscapeCard|TvLoading|Poster|PosterCard|SearchHistoryAction|NavigationButton|ActorCard|Button|IconButton|TextButton|Checkbox|RadioButton|Switch|OutlinedTextField|Image)\s*\('
            for order,match in enumerate(re.finditer(pattern,text)):
                if text[max(0,match.start()-6):match.start()].strip().endswith('fun'): continue
                start=match.end(); depth=1; quote=False;escape=False;end=start
                while end<len(text) and depth:
                    c=text[end]
                    if escape:escape=False
                    elif c=='\\' and quote:escape=True
                    elif c=='"':quote=not quote
                    elif not quote:
                        if c=='(':depth+=1
                        elif c==')':depth-=1
                    end+=1
                args=text[start:end-1];tag=match[1];line=text[:match.start()].count('\n')+1
                icon = re.search(r'\b(?:icon|placeholderIcon)\s*=\s*"([^"]+)"',args)
                direct=re.match(r'\s*"([^"]+)"',args) if tag in ('TvIcon','TvNavIcon') else None
                asset_ids=[canonical((icon or direct)[1],manifest,'tv')] if icon or direct else ['loading'] if tag=='TvLoading' else []
                dynamic=None
                adapter=False
                assigned=re.search(r'\b(?:icon|placeholderIcon)\s*=\s*([^,]+)',args,re.S)
                if not asset_ids and assigned:
                    dynamic=assigned[1].strip()
                    names=kotlin_expression_values(dynamic)
                    if names is not None:asset_ids=[canonical(name,manifest,'tv') for name in names]
                    else:errors.append(f'{rel}:{line}: register dynamic TV action icon {dynamic!r}')
                if tag=='Image' and 'R.drawable.jz_wordmark' in args:asset_ids=['brand-wordmark']
                if not asset_ids and tag in ('TvIcon','TvNavIcon'):
                    dynamic=args.split(',',1)[0].strip();contract=contract_map.get((rel,dynamic))
                    if contract:
                        asset_ids=[canonical(n,manifest,'tv') for n in contract['assets']]
                        adapter=contract.get('adapter',False)
                    else:errors.append(f'{rel}:{line}: register dynamic TV icon {dynamic!r}')
                for name in asset_ids:
                    if name not in registry and not (tag == 'Image' and name == 'brand-wordmark'):errors.append(f'{rel}:{line}: unknown TV icon {name}')
                result.append({'id':f'{rel}:{tag}:{order}','source':rel,'line':line,'platforms':['android-tv'],'category':'asset' if tag in ('TvIcon','TvNavIcon','TvLoading') or (tag=='Image' and asset_ids) else 'media-content' if tag in ('Image','Poster') else 'control','feature':source_family(path),'element':tag,'purpose':compact(args),'assets':asset_ids,'dynamic_expression':dynamic,'display_size':tv_geometry(tag,args,rel,profiles),'target':{'display_environments':['1080p','4K'],'density':'device dependent; record at acceptance'},'states':['normal','focused','selected','disabled','busy'],'accessible_name_owner':'adjacent Text / enclosing native TV control; decorative Icon contentDescription=null','classification':'native TV focus and control contract','source_excerpt':compact(text[match.start():end])})
                if adapter:
                    result[-1]['purpose']=contract['reason']
                    result[-1]['category']='adapter'
                    result[-1]['supported_assets']=result[-1]['assets']
                    result[-1]['assets']=[]
    for source in contracts.get('literal_sources', []):
        text = (ROOT/source).read_text()
        values, unresolved = icon_property_values(text, source.endswith('.vue'))
        for name in values:
            if canonical(name, manifest) not in registry: errors.append(f'{source}: unknown icon literal {name}')
        for expression in unresolved: errors.append(f'{source}: icon property needs an explicit dynamic contract: {expression}')
    for contract in contracts['dynamic_icons']:
        if contract.get('values_source'):
            literal_text=(ROOT/contract['values_source']).read_text()
            literals, _ = icon_property_values(literal_text, contract['values_source'].endswith('.vue'))
            values=set(literals)
            if values!=set(contract['assets']):errors.append(f'{contract["values_source"]}: dynamic icon contract differs from actual values {sorted(values)}')
        if contract.get('adapter') and set(contract['assets'])!=set(registry):errors.append(f'{contract["source"]}: forwarding adapter supported_assets must track registered icon IDs')
    errors.extend(glyph_errors(contracts))
    return result, sorted(set(errors))


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true',help='Read-only: verify committed generated outputs, asset references, inventory and pixel dimensions')
    parser.add_argument('--render-brand',action='store_true',help='Also generate/compare raster exports using separately locked maintenance dependencies')
    parser.add_argument('--allow-incomplete-inventory',action='store_true',help='Bootstrap only: emit inventory while migration is in progress; --check never allows this')
    args=parser.parse_args()
    if args.check and args.allow_incomplete_inventory:parser.error('--check cannot ignore incomplete inventory')
    manifest=read_json('assets.json');tokens=read_json('tokens.json');contracts=read_json('contracts.json')
    registry={a['id']:icon_paths(a) for a in manifest['assets'] if a['category']!='brand'}
    errors=[]
    if len({a['id'] for a in manifest['assets']})!=len(manifest['assets']):errors.append('duplicate asset ID')
    for family in manifest['aliases']:
        for alias,name in aliases_for(manifest,family).items():
            if name not in registry:errors.append(f'{family} alias {alias} references unknown asset {name}')
    requirements,inventory_errors=inventory(manifest,registry,contracts)
    errors.extend(inventory_errors)
    exports=brand_outputs(manifest)
    for path,fmt,units,platform in [
        ('frontend/src/generated/design-icons.js','vue-svg-registry','CSS px','web/mobile-web'),
        ('android-tv/app/src/main/java/org/jzmedia/tv/ui/generated/DesignIcons.kt','compose-imagevector','dp','android-tv'),
    ]:
        exports.append({'path':path,'assets':list(registry),'format':fmt,'dimensions':[24,24],'units':'viewBox','display_units':units,'density':'vector; scales with platform density','transparent':True,'safe_area':'24-unit viewBox; per-master optical spacing','platform':platform,'generator_version':GENERATOR_VERSION,'master_revision':{a['id']:a['revision'] for a in manifest['assets'] if a['category']!='brand'}})
    css,kt=token_outputs(tokens)
    outputs={
        'frontend/src/generated/design-icons.js':web_icons(registry,manifest),
        'frontend/src/generated/design-tokens.css':css,
        'android-tv/app/src/main/java/org/jzmedia/tv/ui/generated/DesignIcons.kt':kotlin_icons(registry,manifest),
        'android-tv/app/src/main/java/org/jzmedia/tv/ui/generated/DesignTokens.kt':kt,
        'design/requirements.json':json_text({'schema_version':1,'generator_version':GENERATOR_VERSION,'requirements':requirements}),
        'design/exports.json':json_text({'schema_version':1,'exports':exports}),
        'design/catalog.json':json_text({'schema_version':1,'assets':manifest['assets'],'aliases':manifest['aliases'],'requirements':requirements,'exports':exports,'platform_rules':tokens['platform_rules'],'platform_profiles':read_json('platform-profiles.json')['profiles'],'contracts':contracts}),
    }
    outputs.update(brand_vector_outputs(exports,manifest))
    if args.render_brand:outputs.update(render_brand(exports,manifest))
    # Hash manifest lets default dependency-free check detect altered/obsolete raster content too.
    raster_paths=[e['path'] for e in exports if e['format'] in ('png','ico')]
    renderer_hash=hashlib.sha256((inspect.getsource(render_brand)+inspect.getsource(brand_outputs)).encode()).hexdigest()
    if args.render_brand:
        outputs['design/raster-hashes.json']=json_text({'generator_version':GENERATOR_VERSION,'renderer_sha256':renderer_hash,'masters':{a['master']:hashlib.sha256((ROOT/a['master']).read_bytes()).hexdigest() for a in manifest['assets'] if a['category']=='brand'},'outputs':{p:hashlib.sha256(outputs[p]).hexdigest() for p in raster_paths}})
    elif (DESIGN/'raster-hashes.json').exists():
        hashes=read_json('raster-hashes.json')
        if hashes.get('renderer_sha256')!=renderer_hash:errors.append('brand renderer rules changed; run --render-brand')
        for p,digest in {**hashes['masters'],**hashes['outputs']}.items():
            if not (ROOT/p).exists() or hashlib.sha256((ROOT/p).read_bytes()).hexdigest()!=digest:errors.append(f'{p}: stale or modified raster source/output; run --render-brand')
    else:errors.append('design/raster-hashes.json: missing; run --render-brand')
    for name,content in outputs.items():
        expected=content.encode() if isinstance(content,str) else content
        path=ROOT/name
        if args.check:
            if not path.exists() or path.read_bytes()!=expected:errors.append(f'{name}: generated output is stale')
        else:
            path.parent.mkdir(parents=True,exist_ok=True)
            if not path.exists() or path.read_bytes()!=expected:path.write_bytes(expected)
    errors.extend(validate_rasters(exports))
    if errors:
        for error in errors:print(error,file=sys.stderr)
        if not args.allow_incomplete_inventory:return 1
    print(f'{"Checked" if args.check else "Generated"}: {len(registry)} functional icons, {len(manifest["assets"])-len(registry)} brand masters, {len(requirements)} UI requirements, {len(exports)} platform exports.')
    return 0


if __name__=='__main__':
    raise SystemExit(main())
